### ISSUE TITLE
Add a Help menu with documentation and issue reporting links

### ISSUE THREAD

**Issue by morjoan** [aws-solutions/aws-media-services-application-mapper#184]
Would be nice to have link from MSAM itself that takes the user straight to GitHub's create an issue page for reporting bugs or requesting features.

**Comment by JimTharioAmazon** [comment]
Let's also add:
Feature Request
Bug Report
Solution Landing Page
Doc link (IG, USAGE, etc?)

**Comment by morjoan** [comment]
Need to present version number as well.

**Comment by morjoan** [comment]
![Screen Shot 2021-12-17 at 9 18 48 AM](https://user-images.githubusercontent.com/33331296/146583082-59986188-0af0-4a8e-ac8a-f5636a4226e2.png)

**Comment by tomgilman** [comment]
Super Cool!

**Comment by morjoan** [comment]
Reopening this to update documentation that references the Tools menu.
