### ISSUE TITLE
SSM Managed Instance tile includes system manager's instance name

### ISSUE THREAD

**Issue by spainala** [aws-solutions/aws-media-services-application-mapper#185]
We need an operator friendly name for a SSM managed Instance.

Please include AWS System Manager's "instance name" in the tile for a SSM Managed Instance.

<img width="928" alt="system manager instance name" src="https://user-images.githubusercontent.com/60242286/107830161-1d30bd00-6d40-11eb-86f6-077ca9ad9332.png">

**Comment by morjoan** [comment]
![Screen Shot 2021-12-15 at 9 59 33 AM](https://user-images.githubusercontent.com/33331296/146240327-63b6bacb-cc69-4153-82a4-e330b6e8c06c.png)
Machine name now displays for managed instances. Support also added for EC2 instances.
