### ISSUE TITLE
Please introduce a method to lock diagrams to prevent unwanted changes

### ISSUE THREAD

**Issue by spainala** [aws-solutions/aws-media-services-application-mapper#186]
Please introduce a method to lock nodes/connectors in a diagram.  It is simple to select a node and mistakenly drag or move the diagram.

It would be really helpful to lock a diagram to prevent changes. If the diagram needs to be changed. Unlock the diagram.  Make changes and then apply the lock to prevent further changes.

**Comment by JimTharioAmazon** [comment]
Changes:
- Add lock icon toggle to top-right of diagrams
- Store lock status per diagram in Settings table
- Disable dragging nodes on diagram surface when locked
- Disable diagram menu items when locked

These menu ids are disabled when a diagram is locked:
```
const menu_ids = ["diagram_manage_contents", "diagram_add_downstream", "diagram_add_upstream",
      "diagram_add_all_nodes", "nodes_align_vertical", "nodes_align_horizontal", "nodes_layout_vertical",
      "nodes_layout_horizontal", "nodes_layout_isolated", "diagram_remove_selected", "diagram_remove_diagram"];
```

**Comment by JimTharioAmazon** [comment]
Top left locked:
![image](https://user-images.githubusercontent.com/33331284/145467222-a51cb2e6-c05c-45ea-8607-e767b436d86a.png)

**Comment by JimTharioAmazon** [comment]
Disabled menu items when locked:
![image](https://user-images.githubusercontent.com/33331284/145467321-f50532a4-e06e-46be-93db-63deacd1e2c8.png)

**Comment by JimTharioAmazon** [comment]
Locked diagrams still accept drag-n-drop nodes, so reopening to disable drop target when locked.
