### ISSUE TITLE
Deprecate build timestamps and use semantic versions for identification

### ISSUE THREAD

**Issue by JimTharioAmazon** [aws-solutions/aws-media-services-application-mapper#197]
Build timestamps are difficult to trace and and are prone to being misread.

**Comment by JimTharioAmazon** [comment]
We received a request today for more detail on how to determine the build timestamp for a specific release in this section of the INSTALL.md guide.

https://github.com/awslabs/aws-media-services-application-mapper/blob/master/docs/INSTALL.md#version-specific-templates

**Comment by morjoan** [comment]
Perhaps as part of this task, update the MSAM Build Numbers under the Tools menu.

**Comment by morjoan** [comment]
Adding version under Help menu will be tracked by #184
