### ISSUE TITLE
Connection dialog "Do Not Remember/Remember" button change request

### ISSUE THREAD

**Issue by spainala** [aws-solutions/aws-media-services-application-mapper#200]
Please consider changing the Connection dialog "Do Not Remember/Remember" button. Today we need to click "Do Not Remember" to reveal the "Remember" button and then save.  A checkbox or other method to save the credentials would simplify this operation.  

https://github.com/awslabs/aws-media-services-application-mapper/blob/master/docs/USAGE.md

**Comment by JimTharioAmazon** [comment]
Here's a new look for @spainala 

![image](https://user-images.githubusercontent.com/33331284/144946060-2cc8f71e-5d8d-47ea-9b81-3e66369eee52.png)
