### ISSUE TITLE
S3 bucket to MediaLive connection mapper missing s3:// URLs

### ISSUE THREAD

**Issue by JimTharioAmazon** [aws-solutions/aws-media-services-application-mapper#227]
We have a match pattern for s3:// URLs, but it appears to be missing the match due to constraints in the pattern and method used in the Python re module.

This isn't matching:
`s3://media-sources-eu-west-3/waves.mp4`

Here is the specific mapper:
https://github.com/awslabs/aws-media-services-application-mapper/blob/master/source/msam/chalicelib/connections.py#L492

**Comment by morjoan** [comment]
@JimTharioAmazon i just tried this out on your sample source URL in the python command line using one of our defined expressions `re.compile(r"s3\:\/\/([^\/]+)")` and I'm getting a match.
What we don't match is something like "s3ssl://.." which is a valid URL. We'll need to accommodate for that.
