### ISSUE TITLE
Support for AWS Elemental MediaLive CDI input type

### ISSUE THREAD

**Issue by spainala** [aws-solutions/aws-media-services-application-mapper#231]
Please consider adding support for AWS Elemental MediaLive CDI input type.

**Comment by morjoan** [comment]
This is already handled by this code: https://github.com/aws-solutions/aws-media-services-application-mapper/blob/main/source/msam/chalicelib/connections.py#L327
![Screen Shot 2021-12-09 at 1 23 47 PM](https://user-images.githubusercontent.com/33331296/145480704-26c72653-f3ab-4e00-b692-d6c4301a9d6e.png)

**Comment by morjoan** [comment]
Current implementation satisfies requirements.
