### ISSUE TITLE
Add HLS/DASH player pop-up to provide a monitor for endpoints

### ISSUE THREAD

**Issue by JimTharioAmazon** [aws-solutions/aws-media-services-application-mapper#34]
We'd like to be able to quickly play back video from various DASH, HLS endpoints, including MediaPackage, MediaConnect, etc.

**Comment by SteveWardAmazon** [comment]
Should have MSS playback too.

**Comment by JimTharioAmazon** [comment]
Can we navigate to MediaPackage's endpoint player for one case?

**Comment by SteveWardAmazon** [comment]
That seems like a reasonable approach.
