### ISSUE TITLE
Add a quick-hide button below the diagram lock

### ISSUE THREAD

**Issue by JimTharioAmazon** [aws-solutions/aws-media-services-application-mapper#349]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Single-click to hide a diagram
Please a close icon below the diagram lock button that hides the diagram

**Describe alternatives you've considered**
We have a menu item that requires a couple of clicks. This should stay for accessibility, but a faster option would be good.

**Additional context**

**Comment by JimTharioAmazon** [comment]
Image of the floating controls on the diagram surface.
<img width="737" alt="image" src="https://user-images.githubusercontent.com/33331284/171675926-4820ff0f-de96-4a4d-87ad-7c4f730109b2.png">

**Comment by morjoan** [comment]
Merged into dev-v1.11.0.
