### ISSUE TITLE
Attach freeform notes or links to any node

### ISSUE THREAD

**Issue by JimTharioAmazon** [aws-solutions/aws-media-services-application-mapper#55]
Operators would like to include reference info with diagram nodes. This may include simple notes or links to other systems related to the selected node. A simple popup compartment to view/click and textarea to edit are probably sufficient.

Add an indicator that the node has "notes" attached.

Show notes in selected item compartment?

**Comment by JimTharioAmazon** [comment]
How do we "activate" the notes view for viewing, editing, a navigating embedded links? A pop-up would work here.
Can we place a small button (i) on nodes to show the notes view?
How/where to we indicate the node has existing notes?

**Comment by JimTharioAmazon** [comment]
We'll need to consider a separate DynamoDB table for notes.

**Comment by JimTharioAmazon** [comment]
Will this one solve the need requested for #62 and #63?

**Comment by JimTharioAmazon** [comment]
I think we can do a markdown-enabled compartment in the lower area called Notes for each node or tile. It can be simple text, or use markdown to add links to outside locations or embed images or other data (?) maybe.

**Comment by JimTharioAmazon** [comment]
Need a new API for this one.
/notes
GET ARN - returns the markdown notes as string
POST ARN markdown - updates that markdown for this ARN

We want to remove notes with removed nodes, but we may want a longer expiration duration on notes in case an ARN is removed and reappears later.

**Comment by JimTharioAmazon** [comment]
We've used showdown for front-end rendering on other projects:
https://github.com/showdownjs/showdown

**Comment by JimTharioAmazon** [comment]
Notes for manage dialog:

1. Please add a close box (top-right) or explicit close button at the bottom, so users won't have to click outside to close it.
2. Would it be possible to limit the rendered HTML in the manage diagram dialog to first 100-200 characters? I would try to reduce the markdown source first and then pass it over to showdown to render. Another option might be a cell formatter that takes it all to support accurate filters, but only draws the first hundred of so characters.

**Comment by morjoan** [comment]
Functionality is pretty much there. Using other issues to track minor tweaks to this feature.
