### ISSUE TITLE
Need a UI mechanism to manage many diagrams

### ISSUE THREAD

**Issue by JimTharioAmazon** [aws-solutions/aws-media-services-application-mapper#58]
The open the tabs approach won't scale for large sets of diagrams. We need a way to simplify the tab bar (auto close after a max open?), and a sortable list or table to choose diagrams to reopen instead of cluttering the tab bar with everything.

**Comment by morjoan** [comment]
We now have a way to limit the number of diagrams shown at a time, automatically hide a diagram (least recently opened) when a new diagram is created or shown after limit has been reached, and show a previously hidden diagram.
