### ISSUE TITLE
MSAM UI performance issue: It takes a moment to respond to clicks

### ISSUE THREAD

**Issue by chrisgel15** [aws-solutions/aws-media-services-application-mapper#67]
Hello!

We have been interacting with MSAM during the past months and our customer reported that the UI does not flow smoothtly to the user interaction.

We have multiple tiles (180 approx) in our production environment, but we were also able to validate this behavior in our QA environment, where we have no more than 20 tiles. Altough in QA seems to work a little bit, we observe that with more tiles it starts to have those delays.

For a reference to what we mean, I am attaching following image:

![ab204f39-39ab-4c24-a608-c080083f81d4](https://user-images.githubusercontent.com/11690066/70148814-ab61db80-1685-11ea-8014-3334c9a933eb.gif)

You can see that there is a delay after the click. 

In order to understand what could be happening behind the scenes, we also captured some network behavior during this operation in case you find it useful:

![e35db30a-a724-4dc7-b3ae-58a43b1d001d](https://user-images.githubusercontent.com/11690066/70151008-b7e83300-1689-11ea-9dd1-d4ea62e57c2a.png)

![61bedc0c-f139-4d39-bbba-059ac061a8a2](https://user-images.githubusercontent.com/11690066/70151015-bcace700-1689-11ea-9727-69c580139962.png)

Let me know if you have any questions.

**Comment by chrisgel15** [comment]
Hello everyone, any updates on this case?

We will appreciate a comment about it.

Thanks,
Christian

**Comment by JimTharioAmazon** [comment]
Hi Christian, sorry for the delay. I'm back from re:Invent this week. Give me another day or two to review this. I assume we'll need to do some profiling of that code to see where our bottleneck is located. Since the delay gets longer with each tile, it should be pretty straightforward for chase down. I'll respond again on Thursday with my findings.

**Comment by chrisgel15** [comment]
That sound great Jim! Thanks!

**Comment by JimTharioAmazon** [comment]
![image](https://user-images.githubusercontent.com/33331284/70663421-25153e80-1c1d-11ea-9865-1c88ce0f6a36.png)

Here is our hot spot in code when selecting a tile. I suspect there is some optimization needed in there. I'll know more tomorrow.

**Comment by chrisgel15** [comment]
Thanks Jim!
Could you also review other navigation interactions like:

- Navigating through the top bar menu
- Navigating through the bottom bar when a tile is selected (the different tabs like: `monitor`) and navigating throught the alarms and alerts.
- Selecting different resources in a diagram.

**Comment by JimTharioAmazon** [comment]
Hi, I have an update to the browser app for you to try. It appeared the tool was going back to the REST API more often than needed - such as retrieving data that would not have changed from a previous call. I introduced memoization to several of the front end functions to reduce the number of back-end calls. I also try to detect when we push a change to the back-end from the browser to invalidate the associated function cache. I will need your help checking this against your large database to assist me understanding how much improvement was gained for you. I'd also like to get a profile capture from Chrome while you're clicking around the tool.

This build is compatible with recent back-end builds, so you can install this separately and just point at an existing endpoint/api-key.

https://rodeolabz-us-west-2.s3.amazonaws.com/msam/msam-browser-app-release-1576190702.template

The changes have also been committed to the repository, but not associated with any release build.

**Comment by chrisgel15** [comment]
Jim, thanks for your quick response.
We will work on what you requested and let you know our findings.

Thanks
Christian
