### ISSUE TITLE
Add Button to UI to Do Something

### ISSUE THREAD

**Issue by estatt01** [aws-solutions/aws-media-services-application-mapper#83]
Based on an alarm, a user may want to take action (what good is an alarm if you cannot resolve the issue?).  This request is to allow a user to add a button.  The action the button takes is up to the user.  It can be a script that fires for example to switch a device from a primary input to a secondary input.

**Comment by JimTharioAmazon** [comment]
Initial thoughts on this one.

**Flow:**

1. Something needs to be selected on the diagram surface (Channel, Bucket, etc.)
2. Depending on the type of node selected, one or more action buttons are shown (somewhere) that are associated with that node type
3. The button sends a POST to an endpoint
4. Response from the endpoint is shown as-is in a pop-up dialog

We need to be able to reference data from the node to build the URL path, parameters, or POST body. Consider using JSONPath notation to make these references.

**Selected node data:**

![image](https://user-images.githubusercontent.com/33331284/74479770-a3cc6900-4e64-11ea-8f9b-578891253058.png)

**Example URL with referenced ARN from the selected node:**
https://actionendpoint.something.else/{$.Arn}

**Example POST body with referenced node data:**
{
    "Command": "SwitchTo",
    "Input": "{$.InputAttachments[1]. InputId}"
{

The {$.Arn} reference above is replaced with the arn of the resource.
The {$.InputAttachments[1]. InputId} reference is replaced with the input ID of the second input in the list.

Security mechanism of the endpoint called by MSAM is outside of this scope.
Button/action/substitution specifications are kept in the Settings table in the cloud

Does the invocation of the endpoint happen at the browser, or is it queued into the AWS account and initiated cloud-side from the AWS network?
